openapi: 3.0.0
info:
  title: API2
  description: API2 doc
  version: 1.0
servers:
  - url: 'https://example.com'
    description: API1 server
paths:
  /api/v2/test:
    get:
      tags:
        - api2
      summary: test
  